spring:
  application:
    name: ecomm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: X-workZodc@123
    url: jdbc:mysql://localhost:3306/ecomm_dev
    username: root

  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create
    show-sql: true

logging:
  file:
    name: ../ecomm/log/Ecomm_log.log
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    net:
      guides: DEBUG


#springdoc:
#    swagger-ui:
#        path: http://localhost:8080/swagger-ui/
#        tryItOutEnabled: true
#        filter: true