spring:
  profiles:
    active: dev
#  application:
#    name: ecomm
#  datasource:
#    url: jdbc:mysql://localhost:3306/xworkz
#    username: root
#    password: X-workZodc@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        ddl-auto: create


logging:
  file:
    name: ../ecomm/log/Ecomm_log.log
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    net:
      guides: DEBUG


#springdoc:
#    swagger-ui:
#        path: http://localhost:8080/swagger-ui/
#        tryItOutEnabled: true
#        filter: true