spring:
    application:
        name: ecomm
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: X-workZodc@123
        url: jdbc:mysql://localhost:3306/xworkz
        username: root
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true

#springdoc:
#    swagger-ui:
#        path: http://localhost:8080/swagger-ui/
#        tryItOutEnabled: true
#        filter: true